
OBJS += $(REPO_DIR)/src/frontends/systemverilog/uhdm_ast.o
OBJS += $(REPO_DIR)/src/frontends/systemverilog/uhdm_ast_frontend.o
OBJS += $(REPO_DIR)/src/frontends/systemverilog/uhdm_common_frontend.o
OBJS += $(REPO_DIR)/src/frontends/systemverilog/uhdm_surelog_ast_frontend.o
