
SYNLIG_OBJS += frontends/systemverilog/uhdm_ast.o
SYNLIG_OBJS += frontends/systemverilog/uhdm_ast_frontend.o
SYNLIG_OBJS += frontends/systemverilog/uhdm_common_frontend.o
SYNLIG_OBJS += frontends/systemverilog/uhdm_surelog_ast_frontend.o
